const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'); const mm=document.querySelector('#minimap'),mx=mm.getContext('2d');
const WORLD=4200,BORDER=80,FOOD_TARGET=650,BOTS=7; let W,H,dpr=1,running=false,last=0,startTime=0,kills=0,best=+localStorage.snakeBest||0; let snakes=[],foods=[],player=null,camera={x:0,y:0};
const $=s=>document.querySelector(s), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), dist2=(a,b)=>(a.x-b.x)**2+(a.y-b.y)**2, TAU=Math.PI*2;
const defaults={swap:false,joySize:120,opacity:70,sensitivity:100,map:true,mapSize:170,mapOpacity:75,bots:true,camera:true}; let settings={...defaults,...JSON.parse(localStorage.snakeSettings||'{}')};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)} addEventListener('resize',resize);resize();
const colors=['#36e3f0','#ffb12b','#b779ff','#55e07a','#ff5f7e','#4e8cff','#f3e55a','#ff8b45'];
function rand(a,b){return a+Math.random()*(b-a)} function safePos(){return {x:rand(350,WORLD-350),y:rand(350,WORLD-350)}}
function makeSnake(name,isPlayer=false,i=0){let p=safePos(),ang=rand(0,TAU),s={name,isPlayer,x:p.x,y:p.y,ang,target:ang,speed:150,radius:13,mass:isPlayer?55:rand(42,85),segments:[],color:isPlayer?'#36e3f0':colors[(i+1)%colors.length],alive:true,shield:3.2,boost:false,aiTimer:0,personality:['collector','hunter','cautious'][i%3],killer:null};for(let j=0;j<55;j++)s.segments.push({x:s.x-Math.cos(ang)*j*6,y:s.y-Math.sin(ang)*j*6});return s}
function spawnFood(n=1,x,y,rich=false){for(let i=0;i<n;i++){let p=x==null?safePos():{x:x+rand(-40,40),y:y+rand(-40,40)};foods.push({x:p.x,y:p.y,v:rich?(Math.random()<.2?5:3):1,r:rich?rand(5,8):rand(3,5),h:Math.random()*360})}}
function reset(){snakes=[];foods=[];kills=0;player=makeSnake('Ты',true);snakes.push(player);for(let i=0;i<BOTS;i++)snakes.push(makeSnake(['Nova','Byte','Viper','Orbit','Mango','Ghost','Rex'][i],false,i));spawnFood(FOOD_TARGET);startTime=performance.now();running=true;document.body.classList.add('playing');$('.overlay.show')?.classList.remove('show')}
function ai(s,dt){s.aiTimer-=dt;if(s.aiTimer>0)return;s.aiTimer=rand(.08,.22);let danger=null,bestD=Infinity;for(const o of snakes){if(o===s||!o.alive)continue;for(let k=0;k<o.segments.length;k+=5){let q=o.segments[k],d=dist2(s,q);if(d<bestD&&d<260**2){bestD=d;danger=q}}}let edge=Math.min(s.x,s.y,WORLD-s.x,WORLD-s.y);if(edge<280){s.target=Math.atan2(WORLD/2-s.y,WORLD/2-s.x);return}if(danger&&s.personality!=='hunter'){s.target=Math.atan2(s.y-danger.y,s.x-danger.x);return}let target=null,score=Infinity;if(s.personality==='hunter'&&player?.alive&&dist2(s,player)<900**2){target=player;score=0}else for(const f of foods){let d=dist2(s,f)/(f.v*f.v);if(d<score){score=d;target=f}}if(target)s.target=Math.atan2(target.y-s.y,target.x-s.x);s.target+=rand(-.08,.08)}
function angleDiff(a,b){return Math.atan2(Math.sin(b-a),Math.cos(b-a))}
function updateSnake(s,dt){if(!s.alive)return;if(!s.isPlayer)ai(s,dt);s.shield=Math.max(0,s.shield-dt);let turn=2.7*(s.isPlayer?settings.sensitivity/100:1);s.ang+=clamp(angleDiff(s.ang,s.target),-turn*dt,turn*dt);let boosting=s.boost&&s.mass>25;let sp=s.speed*(boosting?1.7:1);s.x+=Math.cos(s.ang)*sp*dt;s.y+=Math.sin(s.ang)*sp*dt;if(boosting)s.mass=Math.max(24,s.mass-dt*2.2);let spacing=6,head={x:s.x,y:s.y};s.segments.unshift(head);let max=Math.floor(35+s.mass*1.35);while(s.segments.length>max)s.segments.pop();for(let i=1;i<s.segments.length;i++){let a=s.segments[i-1],b=s.segments[i],dx=a.x-b.x,dy=a.y-b.y,d=Math.hypot(dx,dy)||1;if(d>spacing){b.x=a.x-dx/d*spacing;b.y=a.y-dy/d*spacing}}for(let i=foods.length-1;i>=0;i--){let f=foods[i];if((s.x-f.x)**2+(s.y-f.y)**2<(s.radius+f.r+5)**2){s.mass+=f.v*.7;foods.splice(i,1)}}if(s.shield<=0&&(s.x<BORDER||s.y<BORDER||s.x>WORLD-BORDER||s.y>WORLD-BORDER))die(s,null);if(s.shield<=0)for(const o of snakes){if(o===s||!o.alive)continue;for(let k=8;k<o.segments.length;k+=3){if(dist2(s,o.segments[k])<(s.radius+9)**2){die(s,o);return}}}}
function die(s,killer){if(!s.alive)return;s.alive=false;s.killer=killer;let parts=Math.min(90,Math.floor(s.mass));for(let i=0;i<parts;i++){let q=s.segments[Math.floor(Math.random()*s.segments.length)]||s;spawnFood(1,q.x,q.y,true)}if(killer?.isPlayer)kills++;if(s.isPlayer){best=Math.max(best,Math.floor(s.mass));localStorage.snakeBest=best;setTimeout(showResult,500)}else setTimeout(()=>{let idx=snakes.indexOf(s);if(idx>=0)snakes[idx]=makeSnake(s.name,false,Math.floor(Math.random()*7))},1800)}
function update(dt){if(!running)return;for(const s of snakes)updateSnake(s,dt);while(foods.length<FOOD_TARGET)spawnFood(8);if(player?.alive){camera.x+=(player.x-camera.x)*Math.min(1,dt*6);camera.y+=(player.y-camera.y)*Math.min(1,dt*6)}}
function worldToScreen(x,y){return{x:x-camera.x+W/2,y:y-camera.y+H/2}}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#07151a';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2-camera.x,H/2-camera.y);let grid=100;ctx.strokeStyle='#ffffff08';ctx.lineWidth=1;for(let x=0;x<=WORLD;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,WORLD);ctx.stroke()}for(let y=0;y<=WORLD;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WORLD,y);ctx.stroke()}let g=ctx.createLinearGradient(0,0,BORDER,0);g.addColorStop(0,'#ff314bcc');g.addColorStop(1,'#ff314400');ctx.fillStyle=g;ctx.fillRect(0,0,BORDER,WORLD);ctx.save();ctx.translate(WORLD,0);ctx.scale(-1,1);ctx.fillRect(0,0,BORDER,WORLD);ctx.restore();let gy=ctx.createLinearGradient(0,0,0,BORDER);gy.addColorStop(0,'#ff314bcc');gy.addColorStop(1,'#ff314400');ctx.fillStyle=gy;ctx.fillRect(0,0,WORLD,BORDER);ctx.save();ctx.translate(0,WORLD);ctx.scale(1,-1);ctx.fillRect(0,0,WORLD,BORDER);ctx.restore();ctx.strokeStyle='#ff4058';ctx.shadowColor='#ff243f';ctx.shadowBlur=24;ctx.lineWidth=5;ctx.strokeRect(BORDER/2,BORDER/2,WORLD-BORDER,WORLD-BORDER);ctx.shadowBlur=0;for(const f of foods){ctx.fillStyle=`hsl(${f.h} 85% 65%)`;ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,TAU);ctx.fill()}let leader=snakes.filter(s=>s.alive).sort((a,b)=>b.mass-a.mass)[0];for(const s of snakes){if(!s.alive)continue;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=s.color;ctx.lineWidth=s.radius*1.65;ctx.beginPath();for(let i=s.segments.length-1;i>=0;i--){let p=s.segments[i];if(i===s.segments.length-1)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y)}ctx.stroke();ctx.fillStyle=s.color;ctx.beginPath();ctx.arc(s.x,s.y,s.radius,0,TAU);ctx.fill();let px=Math.cos(s.ang),py=Math.sin(s.ang),sx=-py,sy=px;ctx.fillStyle='#fff';for(const side of [-1,1]){ctx.beginPath();ctx.arc(s.x+px*7+sx*side*5,s.y+py*7+sy*side*5,3.3,0,TAU);ctx.fill()}if(s.shield>0){ctx.strokeStyle='#9ff8ff88';ctx.lineWidth=3;ctx.beginPath();ctx.arc(s.x,s.y,s.radius+9+Math.sin(performance.now()/120)*2,0,TAU);ctx.stroke()}if(s===leader){ctx.font='18px sans-serif';ctx.textAlign='center';ctx.fillText('👑',s.x,s.y-24)}}ctx.restore();if(player?.alive){let edge=Math.min(player.x,player.y,WORLD-player.x,WORLD-player.y);if(edge<350){ctx.fillStyle=`rgba(255,35,60,${(350-edge)/900})`;ctx.fillRect(0,0,W,H)}}drawMap();drawLeaderboard()}
function drawMap(){if(!settings.map){mm.style.display='none';return}mm.style.display='block';let size=+settings.mapSize;mm.style.width=size+'px';mm.style.height=size+'px';mm.style.opacity=settings.mapOpacity/100;mx.clearRect(0,0,180,180);mx.fillStyle='#07151a';mx.fillRect(0,0,180,180);mx.strokeStyle='#ff4058';mx.lineWidth=5;mx.strokeRect(2,2,176,176);let sc=180/WORLD;if(settings.bots)for(const s of snakes){if(!s.alive||s.isPlayer)continue;mx.fillStyle=s.color;mx.beginPath();mx.arc(s.x*sc,s.y*sc,2.4,0,TAU);mx.fill()}if(player){mx.fillStyle='#fff';mx.beginPath();mx.arc(player.x*sc,player.y*sc,4,0,TAU);mx.fill()}if(settings.camera){mx.strokeStyle='#ffffff70';mx.lineWidth=1;mx.strokeRect((camera.x-W/2)*sc,(camera.y-H/2)*sc,W*sc,H*sc)}}
function drawLeaderboard(){let arr=snakes.filter(s=>s.alive).sort((a,b)=>b.mass-a.mass);$('#leaderboard').innerHTML=`<div class='lb-title'>🏆 Лидеры</div>`+arr.slice(0,6).map((s,i)=>`<div class='lb-row ${s.isPlayer?'me':''}'><span>${i+1}. ${s.name}</span><span>${Math.floor(s.mass)}</span></div>`).join('')}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function showResult(){running=false;document.body.classList.remove('playing');let sec=Math.floor((performance.now()-startTime)/1000),rank=[...snakes].sort((a,b)=>b.mass-a.mass).indexOf(player)+1;$('#stats').innerHTML=`<p>Длина: <b>${Math.floor(player.mass)}</b></p><p>Место: <b>${rank}</b></p><p>Уничтожено: <b>${kills}</b></p><p>Время: <b>${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}</b></p><p>Рекорд: <b>${best}</b></p>`;$('#result').classList.add('show')}
// Desktop controls
canvas.addEventListener('mousemove',e=>{if(!player?.alive)return;player.target=Math.atan2(e.clientY-H/2,e.clientX-W/2)});let keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'&&player)player.boost=true});addEventListener('keyup',e=>{keys[e.code]=false;if(e.code==='Space'&&player)player.boost=false});setInterval(()=>{if(!player?.alive)return;let x=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),y=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0);if(x||y)player.target=Math.atan2(y,x)},16);
// Mobile joystick
let joy=$('#joystick'),stick=$('#stick'),joyId=null;function joyMove(e){let r=joy.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),m=r.width*.34,d=Math.hypot(x,y)||1,k=Math.min(1,m/d);stick.style.transform=`translate(${x*k}px,${y*k}px)`;if(player)player.target=Math.atan2(y,x)}joy.addEventListener('pointerdown',e=>{joyId=e.pointerId;joy.setPointerCapture(joyId);joyMove(e)});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)joyMove(e)});joy.addEventListener('pointerup',e=>{joyId=null;stick.style.transform='translate(0,0)'});$('#boost').addEventListener('pointerdown',()=>{if(player)player.boost=true});['pointerup','pointercancel','pointerleave'].forEach(ev=>$('#boost').addEventListener(ev,()=>{if(player)player.boost=false}));
function applySettings(){joy.style.width=joy.style.height=settings.joySize+'px';joy.style.opacity=settings.opacity/100;$('#boost').style.opacity=settings.opacity/100;if(settings.swap){joy.style.left='auto';joy.style.right='28px';$('#boost').style.right='auto';$('#boost').style.left='36px'}else{joy.style.right='auto';joy.style.left='28px';$('#boost').style.left='auto';$('#boost').style.right='36px'}$('#swapControls').checked=settings.swap;$('#joySize').value=settings.joySize;$('#controlOpacity').value=settings.opacity;$('#sensitivity').value=settings.sensitivity;$('#mapEnabled').checked=settings.map;$('#mapSize').value=settings.mapSize;$('#mapOpacity').value=settings.mapOpacity;$('#showBots').checked=settings.bots;$('#showCamera').checked=settings.camera}
function saveSettings(){settings={swap:$('#swapControls').checked,joySize:+$('#joySize').value,opacity:+$('#controlOpacity').value,sensitivity:+$('#sensitivity').value,map:$('#mapEnabled').checked,mapSize:+$('#mapSize').value,mapOpacity:+$('#mapOpacity').value,bots:$('#showBots').checked,camera:$('#showCamera').checked};localStorage.snakeSettings=JSON.stringify(settings);applySettings()}
['swapControls','joySize','controlOpacity','sensitivity','mapEnabled','mapSize','mapOpacity','showBots','showCamera'].forEach(id=>$('#'+id).addEventListener('input',saveSettings));applySettings();
$('#playBtn').onclick=reset;$('#again').onclick=()=>{$('#result').classList.remove('show');reset()};$('#home').onclick=()=>{$('#result').classList.remove('show');$('#menu').classList.add('show')};function openSettings(){$('#settings').classList.add('show')}$('#settingsBtn').onclick=openSettings;$('#menuSettings').onclick=openSettings;$('#closeSettings').onclick=()=>$('#settings').classList.remove('show');
